name: Python Package

on: 
  push:
    paths:
      - 'hubdata/input/**' # Only run when changes are pushed to this directory

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate  
        python -m pip install --upgrade pip
        pip install -r data/requirements.txt

    - name: Test
      run: |
        source venv/bin/activate
        # python data/myscript.py
        PYTHONPATH=. pytest data/test/test_data.py

